=== auh2oj/dundermifflin/src/main/webapp/WEB-INF/employee-soap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.dundermifflin.com/employee-soap"
xmlns:tns="http://www.dundermifflin.com/employee-soap" elementFormDefault="qualified">

<!-- Root element of the XML instance document created by this XSD file -->
<element name="employees" type="tns:Employees" />

<complexType name="Employees">

	<sequence>
		<element name="employee" type="tns:Employee" minOccurs="0" maxOccurs="unbounded" />
	</sequence>

</complexType>

<!-- Analogous to Employee class -->
<complexType name="Employee">

	<sequence>
		<element name="name" type="string" minOccurs="1" maxOccurs="1" />
		<element name="email" type="string" minOccurs="0" maxOccurs="1" />
		<element name="department" type="string" minOccurs="0" maxOccurs="1" />
		<element name="branch" type="string" minOccurs="0" maxOccurs="1" />
	</sequence>
	<attribute name="id" type="int" default="1" />

</complexType>

</schema>

=== auh2oj/dundermifflin/src/main/webapp/WEB-INF/employee-soap.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:employees xmlns:tns="http://www.dundermifflin.com/employee-soap"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dundermifflin.com/employee-soap employee-soap.xsd ">
	
	<tns:employee id="100">
		<tns:name>Michael Scott</tns:name>
		<tns:email>mscott@dm.com</tns:email>
		<tns:department>Manager</tns:department>
		<tns:branch>Scranton, PA</tns:branch>
	</tns:employee>
	
	<tns:employee id="200">
		<tns:name>Jim Halpert</tns:name>
		<tns:email>jhalpert@dm.com</tns:email>
		<tns:department>Sales</tns:department>
		<tns:branch>Scranton, PA</tns:branch>
	</tns:employee>
	
	<tns:employee id="300">
		<tns:name>Dwight Schrute</tns:name>
		<tns:email>dschrute@dm.com</tns:email>
		<tns:department>Sales</tns:department>
		<tns:branch>Scranton, PA</tns:branch>
	</tns:employee>
	
</tns:employees>
